Vertex, Matrix classes implemented & graph class changes
Secret333Boy/utoolslib pull request #17
Opened 2021-09-14 01:47 UTC by Secret333Boy

Issue #16

2021-09-15 14:50 UTC, GrigoriyUstymenko requested changes
All in all good, needs some minor changes.

2021-09-15 14:50 UTC, GrigoriyUstymenko commented on src/tools/dataStructures/Matrix.js
> +    }
```suggestion
    for (const i in this.arr) {
      for (const j in this.arr[i]) {
        res[j][i] = this.arr[i][j];
      }
    }
```

2021-09-15 14:50 UTC, GrigoriyUstymenko commented on src/tools/dataStructures/Matrix.js
> +        this.arr[i][j] = this.arr[i][0] + matrix.arr[0][j];
Why not multiplication? Also use for in.

2021-09-16 18:55 UTC, Secret333Boy commented on src/tools/dataStructures/Matrix.js
> +    return this.arr[(y, x)];
Just a typo. I should test first

2021-09-16 18:56 UTC, Secret333Boy commented on src/tools/dataStructures/Matrix.js
> +    }
Good idea!

2021-09-18 17:34 UTC, GrigoriyUstymenko approved these changes
Looks good

2021-09-18 17:35 UTC, merged