Text encryptor
Secret333Boy/utoolslib pull request #2
Opened 2021-05-27 16:54 UTC by Secret333Boy

Text encryptor is ready

2021-05-27 20:14 UTC, GrigoriyUstymenko requested changes
All in all, pretty good.

2021-05-27 20:14 UTC, GrigoriyUstymenko commented on src/tools/textEncryptor/textEncryptor.js
> +      fs.writeFileSync(path, this.encryptString(data));
It would probably be a good idea to catch errors within writeFileSync with try catch

2021-05-27 20:14 UTC, GrigoriyUstymenko commented on src/tools/textEncryptor/textEncryptor.js
> +    for (let i = 0; i < data.length; i++) {
Why not turn data into an array and iterate using .map?
Though your implementation is good too
```suggestion
    const newData = data.split('').map((char) => {
      const code = this._modifyCode(char.charCodeAt(0));
      return String.fromCharCode(code);
    };
```

2021-05-27 20:14 UTC, GrigoriyUstymenko commented on tests/textEncryptor/textEncryptor.js
> +}
I think the error itself should be displayed
```suggestion
  for (const par of tests.pars) {
    try {
      const TE = new TextEncryptor(seed);
      console.log(` ${par}: `);
      assert.notDeepEqual(TE.encryptString(par), par);
      assert.deepEqual(TE.encryptString(TE.encryptString(par)), par);
      console.log('SUCCESS');
    } catch (error) {
      console.log('FAILED: ' + error);
      continue;
    }
  }
}
```

2021-05-30 08:56 UTC, GrigoriyUstymenko commented on src/tools/textEncryptor/textEncryptor.js
> +      _enternalSeed: {
```suggestion
      _internalSeed: {
```

2021-05-30 14:15 UTC, Secret333Boy reviewed
All changes were approved in the new commit

2021-05-30 16:10 UTC, GrigoriyUstymenko requested changes
Other than these little mistakes, all good.

2021-05-30 16:10 UTC, GrigoriyUstymenko commented on src/tools/textEncryptor/textEncryptor.js
> +    // eslint-disable-next-line eqeqeq
Comments should be deleted (sorry not noticed this the first time)
```suggestion
```

2021-05-30 16:10 UTC, GrigoriyUstymenko commented on src/tools/textEncryptor/textEncryptor.js
> +    return newData;
I think you forgot .join
```suggestion
    return newData.join('');
```

2021-05-30 16:10 UTC, GrigoriyUstymenko commented on tests/textEncryptor/textEncryptor.js
> +    // eslint-disable-next-line max-len
```suggestion
```

2021-05-30 16:44 UTC, GrigoriyUstymenko approved these changes
Great, ready to merge

2021-05-30 17:15 UTC, merged